// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_maximum_jumping_distance = "CgkI_vDQ3ZYdEAIQBg"; // <GPGSID>
        public const string achievement_jump_advanced_person = "CgkI_vDQ3ZYdEAIQBQ"; // <GPGSID>
        public const string achievement_jump_master = "CgkI_vDQ3ZYdEAIQBw"; // <GPGSID>
        public const string achievement_huh_cant_fly = "CgkI_vDQ3ZYdEAIQBA"; // <GPGSID>
        public const string achievement_the_solar_system_is_mine = "CgkI_vDQ3ZYdEAIQAw"; // <GPGSID>
        public const string achievement_first_jump = "CgkI_vDQ3ZYdEAIQAQ"; // <GPGSID>
        public const string achievement_space_came_foooooooo = "CgkI_vDQ3ZYdEAIQAg"; // <GPGSID>
        public const string achievement_item_complete = "CgkI_vDQ3ZYdEAIQCA"; // <GPGSID>

}

